name: Deploy
on:
  push:
    branches:
      - 'deploy/0.17.2-cp314'
jobs:
  wheel-build:
    name: Build qiskit-aer wheels
    strategy:
      matrix:
        os: ["macos-15-intel", "macos-latest", "ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    environment: release
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        if: runner.os == 'Windows'
      - name: Install deps
        run: python -m pip install -U cibuildwheel==3.2.1
      - name: Build Wheels
        env:
          AER_CMAKE_OPENMP_BUILD: 1
        run: cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
          name: aer-deploy-shared-wheel-build-${{ matrix.os }}
  publish-shared-wheels:
    name: Publish shared wheels
    runs-on: ubuntu-latest
    needs: [wheel-build]
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: deploy
          pattern: 'aer-deploy-shared-*'
          merge-multiple: true
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: deploy
